minecraft_version=26.1
java_version=25
forge_version=26.1-62.0.4
forge_major_version=62
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1
neoforge_version=26.1.0.7-beta
neoform_version=26.1-1
enabled_platforms=fabric,neoforge
