minecraft_version=26.1.2
java_version=25
forge_version=26.1.2-64.1.0
forge_major_version=64
fabric_loader_version=0.19.5
fabric_api_version=0.155.2+26.1.2
neoforge_version=26.1.2.104
neoform_version=26.1.2-1
enabled_platforms=forge,fabric,neoforge
