minecraft_version=26.2
java_version=25
forge_version=26.2-65.1.0
forge_major_version=65
fabric_loader_version=0.19.5
fabric_api_version=0.159.0+26.2
neoforge_version=26.2.0.77
neoform_version=26.2-1
enabled_platforms=forge,fabric,neoforge
